version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t succeeds .
      - run:
          name: Test Docker image
          command: |
            docker run -d -p 8080:8080 --name succeeds succeeds
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag succeeds $DOCKERHUB_USERNAME/succeeds:latest
            docker push $DOCKERHUB_USERNAME/succeeds:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build